# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rebs_cash', '0001_initial'),
        ('rebs_contract', '0001_initial'),
        ('rebs_project', '0001_initial'),
        ('rebs_company', '0001_initial'),
        ('rebs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespricebygt',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_contract.ordergroup', verbose_name='차수'),
        ),
        migrations.AddField(
            model_name='salespricebygt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='salespricebygt',
            name='unit_floor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_project.unitfloortype', verbose_name='층별타입'),
        ),
        migrations.AddField(
            model_name='salespricebygt',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_project.unittype', verbose_name='타입'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_cash.projectbankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebs_contract.contract', verbose_name='계약일련번호'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='installment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebs_cash.installmentpaymentorder', verbose_name='납부회차'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='is_refund_closing',
            field=models.ForeignKey(blank=True, help_text='이 건 거래가 환불금 출금인 경우 이 건을 납부한 계약자를 선택', null=True, on_delete=django.db.models.deletion.PROTECT, to='rebs_contract.contractor', verbose_name='환불 계약자'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project_account_d1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rebs.projectaccountd1', verbose_name='현장 계정'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project_account_d2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rebs.projectaccountd2', verbose_name='현장 세부계정'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='recoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_cash.bankcode', verbose_name='은행코드'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='installmentpaymentorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='installmentpaymentamount',
            name='payment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_cash.installmentpaymentorder', verbose_name='납입 회차'),
        ),
        migrations.AddField(
            model_name='installmentpaymentamount',
            name='sales_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_cash.salespricebygt', verbose_name='타입별 분양가'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_cash.bankcode', verbose_name='은행코드'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_company.company', verbose_name='회사정보'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebs_company.department', verbose_name='부서정보'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebs.accountsubd3', verbose_name='세부계정'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_cash.companybankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_company.company', verbose_name='회사정보'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='recoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
