# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebs_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rebs_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rebs_contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rebs_contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractoraddress',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rebs_contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractoraddress',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rebs_contract.contract', verbose_name='계약 정보'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contract',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_contract.ordergroup', verbose_name='차수'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contract',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
