# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubD1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '01. 계정과목 (대분류',
                'verbose_name_plural': '01. 계정과목 (대분류)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSubD2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs.accountsubd1')),
            ],
            options={
                'verbose_name': '02. 계정과목 (중분류)',
                'verbose_name_plural': '02. 계정과목 (중분류)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAccountD1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('1', '수입'), ('2', '지출'), ('3', '대체')], max_length=1, verbose_name='구분')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'A. 프로젝트 계정',
                'verbose_name_plural': 'A. 프로젝트 계정',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WiseSaying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying_ko', models.CharField(max_length=300)),
                ('saying_en', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': '오늘의 한마디',
                'verbose_name_plural': '오늘의 한마디',
            },
        ),
        migrations.CreateModel(
            name='ProjectAccountD2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('sub_title', models.CharField(blank=True, default='', help_text='중분류 항목이 존재할 경우 기재', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs.projectaccountd1')),
            ],
            options={
                'verbose_name': 'B. 프로젝트 세부계정',
                'verbose_name_plural': 'B. 프로젝트 세부계정',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AccountSubD3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('is_special', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=50)),
                ('d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs.accountsubd2')),
            ],
            options={
                'verbose_name': '03. 계정과목 (소분류)',
                'verbose_name_plural': '03. 계정과목 (소분류)',
                'ordering': ['id'],
            },
        ),
    ]
