# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('salt', models.CharField(blank=True, max_length=10, verbose_name='Salt')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff(관리자) 승인 여부', verbose_name='관리자로 승인')),
                ('contract', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='분양 계약 관리')),
                ('payment', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='분양 수납 관리')),
                ('notice', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='고객 고지 관리')),
                ('project_cash', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='현장 자금 관리')),
                ('project_docs', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='현장 문서 관리')),
                ('project', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='신규 프로젝트')),
                ('company_cash', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 회계 관리')),
                ('company_docs', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 문서 관리')),
                ('human_resource', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 인사 관리')),
                ('company_settings', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='회사 관련설정')),
                ('auth_manage', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='권한 설정 관리')),
            ],
            options={
                'verbose_name': '스태프 권한',
                'verbose_name_plural': '스태프 권한',
            },
        ),
    ]
