# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True, verbose_name='계약 일련 번호')),
                ('activation', models.BooleanField(default=True, verbose_name='계약 활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '02. 계약 정보',
                'verbose_name_plural': '02. 계약 정보',
                'ordering': ('-project', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='계약자명')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], max_length=1, null=True, verbose_name='성별')),
                ('is_registed', models.BooleanField(blank=True, default=False, verbose_name='인가등록여부')),
                ('status', models.CharField(choices=[('1', '청약'), ('2', '계약'), ('3', '청약해지'), ('4', '계약해지')], max_length=1, verbose_name='현재상태')),
                ('reservation_date', models.DateField(blank=True, null=True, verbose_name='청약일자')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='계약일자')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '03. 계약자 정보',
                'verbose_name_plural': '03. 계약자 정보',
            },
        ),
        migrations.CreateModel(
            name='ContractorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('id_address1', models.CharField(max_length=50, verbose_name='주민등록 주소')),
                ('id_address2', models.CharField(blank=True, default='', max_length=30, verbose_name='상세주소')),
                ('id_address3', models.CharField(blank=True, default='', max_length=30, verbose_name='참고항목')),
                ('dm_zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('dm_address1', models.CharField(max_length=50, verbose_name='우편송부 주소')),
                ('dm_address2', models.CharField(blank=True, default='', max_length=30, verbose_name='상세주소')),
                ('dm_address3', models.CharField(blank=True, default='', max_length=30, verbose_name='참고항목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '04. 계약자 주소',
                'verbose_name_plural': '04. 계약자 주소',
            },
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(max_length=13, verbose_name='휴대전화')),
                ('home_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='집 전화')),
                ('other_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='기타 전화')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '05. 계약자 연락처',
                'verbose_name_plural': '05. 계약자 연락처',
            },
        ),
        migrations.CreateModel(
            name='ContractorRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('3', '신청 중'), ('4', '처리완료'), ('5', '신청취소')], max_length=1, verbose_name='상태')),
                ('refund_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='환불(예정)금액')),
                ('refund_account_bank', models.CharField(blank=True, max_length=20, verbose_name='환불계좌(은행)')),
                ('refund_account_number', models.CharField(blank=True, max_length=30, verbose_name='환불계좌(번호)')),
                ('refund_account_depositor', models.CharField(blank=True, max_length=30, verbose_name='환불계좌(예금주)')),
                ('request_date', models.DateField(verbose_name='해지신청일')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='해지(환불)처리일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '06. 계약 해지 정보',
                'verbose_name_plural': '06. 계약 해지 정보',
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='차수')),
                ('sort', models.CharField(choices=[('1', '일반분양'), ('2', '조합원')], max_length=1, verbose_name='구분')),
                ('order_group_name', models.CharField(max_length=20, verbose_name='차수명')),
            ],
            options={
                'verbose_name': '01. 차수 (계약그룹)',
                'verbose_name_plural': '01. 차수 (계약그룹)',
                'ordering': ['-project', 'order_number', '-id'],
            },
        ),
    ]
