# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebs_project', '0001_initial'),
        ('rebs_cash', '0002_auto_20210116_2200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBillIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, verbose_name='시행자명')),
                ('host_tel', models.CharField(max_length=13, verbose_name='시행사 전화')),
                ('agency', models.CharField(blank=True, max_length=20, verbose_name='대행사명')),
                ('agency_tel', models.CharField(blank=True, max_length=13, verbose_name='대행사 전화')),
                ('bank_account1', models.CharField(max_length=20, verbose_name='수납은행[1]')),
                ('bank_number1', models.CharField(max_length=20, verbose_name='계좌번호[1]')),
                ('bank_host1', models.CharField(max_length=15, verbose_name='예금주[1]')),
                ('bank_account2', models.CharField(blank=True, max_length=20, verbose_name='수납은행[2]')),
                ('bank_number2', models.CharField(blank=True, max_length=20, verbose_name='계좌번호[2]')),
                ('bank_host2', models.CharField(blank=True, max_length=15, verbose_name='예금주[2]')),
                ('zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('address1', models.CharField(max_length=50, verbose_name='주소')),
                ('address2', models.CharField(blank=True, default='', max_length=30, verbose_name='상세주소')),
                ('address3', models.CharField(blank=True, default='', max_length=30, verbose_name='참고항목')),
                ('title', models.CharField(max_length=255, verbose_name='고지서 제목')),
                ('content', models.TextField(verbose_name='고지서 내용')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 변경일')),
                ('now_payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_cash.installmentpaymentorder', verbose_name='현재 발행회차')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_project.project', verbose_name='프로젝트')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
        ),
    ]
