# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='회사명')),
                ('tax_number', models.CharField(max_length=12, verbose_name='사업자등록번호')),
                ('ceo', models.CharField(max_length=30, verbose_name='대표자명')),
                ('org_number', models.CharField(max_length=14, verbose_name='법인등록번호')),
                ('business_cond', models.CharField(blank=True, max_length=20, verbose_name='업태')),
                ('business_even', models.CharField(blank=True, max_length=20, verbose_name='종목')),
                ('es_date', models.DateField(blank=True, null=True, verbose_name='설립일자')),
                ('op_date', models.DateField(blank=True, null=True, verbose_name='개업일자')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=50, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=30, verbose_name='상세주소')),
                ('address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '01. 회사 정보',
                'verbose_name_plural': '01. 회사 정보',
                'db_table': 'rebs_company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='부서명')),
                ('task', models.CharField(max_length=100, verbose_name='주요 업무')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebs_company.company')),
            ],
            options={
                'verbose_name': '02. 부서 정보',
                'verbose_name_plural': '02. 부서 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='직원 성명')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('entered_date', models.DateField(verbose_name='입사일')),
                ('personal_phone', models.CharField(blank=True, max_length=13, verbose_name='휴대전화')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('status', models.CharField(choices=[('1', '근무 중'), ('2', '정직 중'), ('3', '퇴사신청'), ('4', '퇴사처리')], default='1', max_length=1, verbose_name='상태')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebs_company.company', verbose_name='회사 정보')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebs_company.department', verbose_name='부서 정보')),
            ],
            options={
                'verbose_name': '03. 직원 정보',
                'verbose_name_plural': '03. 직원 정보',
            },
        ),
    ]
