# Generated by Django 3.1.5 on 2021-01-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rebs_project', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffauth',
            name='allowed_projects',
            field=models.ManyToManyField(help_text='조회 및 관리할 수 있는 프로젝트들을 선택합니다.', related_name='allowed_projects', to='rebs_project.Project', verbose_name='허용 프로젝트'),
        ),
        migrations.AddField(
            model_name='staffauth',
            name='assigned_project',
            field=models.ForeignKey(help_text='선택한 프로젝트를 각 화면에서 기본 프로젝트로 보여줍니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project', to='rebs_project.project', verbose_name='담당 메인 프로젝트'),
        ),
        migrations.AddField(
            model_name='staffauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
